package Model;
// Generated Sep 22, 2012 1:35:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private String countrycode;
     private int regioncode;
     private String name;
     private Set airports = new HashSet(0);

    public Country() {
    }

	
    public Country(String countrycode, int regioncode, String name) {
        this.countrycode = countrycode;
        this.regioncode = regioncode;
        this.name = name;
    }
    public Country(String countrycode, int regioncode, String name, Set airports) {
       this.countrycode = countrycode;
       this.regioncode = regioncode;
       this.name = name;
       this.airports = airports;
    }
   
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }
    public int getRegioncode() {
        return this.regioncode;
    }
    
    public void setRegioncode(int regioncode) {
        this.regioncode = regioncode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAirports() {
        return this.airports;
    }
    
    public void setAirports(Set airports) {
        this.airports = airports;
    }




}


