/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateChangePlaneView.java
 *
 * Created on 15-jan-2010, 14:39:41
 */

package View;


import Controller.InputChecker;
import Model.Plane;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeroen
 */
public class CreateChangePlaneView extends javax.swing.JInternalFrame {

    private Plane plane = null;

    /** Creates new form CreateChangePlaneView */
    public CreateChangePlaneView(Plane p) {
        initComponents();
        plane = p;

        if(p != null){
            FillFields();
			txtFieldNumber.setEditable(false);
        }
    }

    private void FillFields(){
        txtFieldNumber.setText(""+plane.getNumber());
        txtFieldCapacity.setText(""+plane.getCapacity());
        txtFieldType.setText( plane.getType());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFieldNumber = new javax.swing.JTextField();
        txtFieldType = new javax.swing.JTextField();
        txtFieldCapacity = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 400));
        setRequestFocusEnabled(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flyaway.FlyAWayApp.class).getContext().getResourceMap(CreateChangePlaneView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txtFieldNumber.setText(resourceMap.getString("txtFieldNumber.text")); // NOI18N
        txtFieldNumber.setName("txtFieldNumber"); // NOI18N

        txtFieldType.setName("txtFieldType"); // NOI18N

        txtFieldCapacity.setName("txtFieldCapacity"); // NOI18N

        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        lblError.setText(resourceMap.getString("lblError.text")); // NOI18N
        lblError.setName("lblError"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(464, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFieldCapacity, txtFieldNumber, txtFieldType});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFieldCapacity, txtFieldNumber, txtFieldType});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String type = txtFieldType.getText();
        int capacity = -1;
        int planeNumber = -1;
		
		lblError.setText("");
		String ErrorMessage = "<html>";
        
		InputChecker ip = new InputChecker();
		
		try{
			planeNumber = Integer.parseInt(txtFieldNumber.getText());
			
			if(Controller.Controller.Instance().getPlaneByNumber(planeNumber) != null && plane == null){
				ErrorMessage += "Plane already exists with planenumber: " + planeNumber + " <br>";
			}
			
		}catch(NumberFormatException nfe){
			ErrorMessage += "Planenumber is not a valid number. <br>";
		}
	
        if(!ip.checkText(type, true, true)){
            ErrorMessage += "No type entered. <br>";
        }
		
		if(!ip.checkMaxLength(type, 50)){
			ErrorMessage += "Type has a maximum length of 50 chars. <br>";	
		}
       
		try{
			capacity = Integer.parseInt(txtFieldCapacity.getText());
			
			if(!ip.checkNumberRange(capacity, 1, 1000)){
				ErrorMessage += "Capacity must be a number in the range of 1-1000. <br>";
			}
			
		}catch(NumberFormatException nfe){
			ErrorMessage += "Capacity is not a valid number. <br>";
		}
        
		ErrorMessage += "</html>";
		
        if(ErrorMessage.equals("<html></html>")){
            
			if (plane == null) {
				plane = new Plane(planeNumber, type, capacity);

				if(Controller.Controller.Instance().saveObject(plane)){
					JOptionPane.showMessageDialog(null, "Plane saved");
					this.dispose();
				}else{
					JOptionPane.showMessageDialog(null, "Error saving plane");
					this.dispose();
				}

			} else {

				plane.setNumber(planeNumber);
				plane.setType(type);
				plane.setCapacity(capacity);

				if(Controller.Controller.Instance().updateObject(plane)){
					JOptionPane.showMessageDialog(null, "Plane saved");
					this.dispose();
				}else{
					JOptionPane.showMessageDialog(null, "Error saving plane");
					this.dispose();
				}

			}
                
        }
        else{
            lblError.setText(ErrorMessage);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtFieldCapacity;
    private javax.swing.JTextField txtFieldNumber;
    private javax.swing.JTextField txtFieldType;
    // End of variables declaration//GEN-END:variables

}
