/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScheduleView.java
 *
 * Created on 25-sep-2012, 15:12:25
 */
package View;

import Controller.Controller;
import Model.Flight;
import Model.Staff;
import java.util.ArrayList;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Tom
 */
public class ScheduleView extends javax.swing.JInternalFrame {

	/** Creates new form ScheduleView */
	public ScheduleView() {
		initComponents();
		Staff s = Controller.Instance().getLogedIn().getStaffAccount();
		
		txtLabelUser.setText("Schedule for staffmember: " + s.getName());
		
		fillTable();
		
	}

	private void fillTable(){
		ArrayList<Flight> flights = Controller.Instance().getScheduledFlights();
       GenericTableModel<Flight> flightsModel = new GenericTableModel<Flight>(flights);
         tblSchedule.setModel(flightsModel);
          TableColumnModel tcm = tblSchedule.getColumnModel();
        CustomTableCellRenderer tcr = new CustomTableCellRenderer();
        for(int it = 0; it < flightsModel.getColumnCount(); it++){
            tcm.getColumn(it).setCellRenderer(tcr);
        }
		if(flights.isEmpty()){
			txtFlights.setText("You are currently not scheduled for any flights");
		}
    }
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtLabelUser = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        txtFlights = new javax.swing.JLabel();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flyaway.FlyAWayApp.class).getContext().getResourceMap(ScheduleView.class);
        txtLabelUser.setText(resourceMap.getString("txtLabelUser.text")); // NOI18N
        txtLabelUser.setName("txtLabelUser"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblSchedule.setName("tblSchedule"); // NOI18N
        jScrollPane2.setViewportView(tblSchedule);

        txtFlights.setText(resourceMap.getString("txtFlights.text")); // NOI18N
        txtFlights.setName("txtFlights"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(txtLabelUser)
                    .addComponent(txtFlights))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLabelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFlights)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JLabel txtFlights;
    private javax.swing.JLabel txtLabelUser;
    // End of variables declaration//GEN-END:variables
}
